# Generated by Django 3.1.2 on 2020-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200)),
                ('produto_marca', models.CharField(max_length=100)),
                ('produto_categoria', models.CharField(max_length=100)),
                ('produto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('produto_estoque', models.IntegerField(default=1)),
                ('produto_avaliacao', models.IntegerField(default=1)),
            ],
        ),
    ]
